package pl.pollub.footballapp;

public enum EventType {
    MATCH_START,
    MATCH_END,
    SECOND_HALF_START,
    OT_FIRST_HALF_START,
    OT_SECOND_HALF_START,
    PENALTIES_START,
    GOAL,
    ASSIST,
    YELLOW_CARD,
    RED_CARD,
    FREE_KICK,
    PENALTY,
    FIRST_HALF_END,
    SECOND_HALF_END,
    OT_FIRST_HALF_END,
    OT_SECOND_HALF_END,
    SUB_IN,
    SUB_OFF,
    SHOT_MISSED,
    SHOT_ON_GOAL,
    ACCURATE_PASS,
    MISSED_PASS,
    OFFSIDE
}
